# 1. Install and Import Dependencies

In [1]:
!pip3 install torch torchvision torchaudio

In [2]:
!pip3 install transformers

     ---------------------------------------- 4.0/4.0 MB 3.4 MB/s eta 0:00:00
     ---------------------------------------- 77.9/77.9 KB 2.2 MB/s eta 0:00:00
     ---------------------------------------- 78.4/78.4 KB 2.2 MB/s eta 0:00:00
     -------------------------------------- 895.2/895.2 KB 3.8 MB/s eta 0:00:00
     -------------------------------------- 151.7/151.7 KB 2.2 MB/s eta 0:00:00
  Using cached filelock-3.6.0-py3-none-any.whl (10.0 kB)
     ---------------------------------------- 3.3/3.3 MB 3.8 MB/s eta 0:00:00
     -------------------------------------- 262.0/262.0 KB 3.2 MB/s eta 0:00:00
     ---------------------------------------- 96.6/96.6 KB 2.8 MB/s eta 0:00:00


In [3]:
!pip3 install requests

In [4]:
!pip3 install beautifulsoup4

In [5]:
!pip3 install pandas

     ---------------------------------------- 10.6/10.6 MB 3.6 MB/s eta 0:00:00
     -------------------------------------- 503.5/503.5 KB 3.5 MB/s eta 0:00:00


In [6]:
!pip3 install numpy

In [7]:
#!pip3 install pandas requests BeautifulSoup4

In [8]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import requests
from bs4 import BeautifulSoup
import re

# 2.Instantiate(Represent) Model

In [9]:
tokenizer = AutoTokenizer.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')

model = AutoModelForSequenceClassification.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')

Downloading:   0%|          | 0.00/39.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/953 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/851k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/638M [00:00<?, ?B/s]

# 3. Encode and Calculate Sentiments

In [32]:
tokens = tokenizer.encode('I hated this, absolutely the worst', return_tensors = 'pt')

In [33]:
tokens

tensor([[  101,   151, 39487, 10163, 10372,   117, 35925, 10563, 10103, 43060,
           102]])

In [34]:
tokens[0]

tensor([  101,   151, 39487, 10163, 10372,   117, 35925, 10563, 10103, 43060,
          102])

In [35]:
#tokenizer.decode(tokens[0])

In [36]:
result = model(tokens)

In [37]:
result

SequenceClassifierOutput(loss=None, logits=tensor([[ 4.8750,  1.7880, -0.8356, -3.0027, -2.0727]],
       grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [38]:
result.logits

tensor([[ 4.8750,  1.7880, -0.8356, -3.0027, -2.0727]],
       grad_fn=<AddmmBackward0>)

In [39]:
torch.argmax(result.logits)

tensor(0)

In [40]:
int(torch.argmax(result.logits))

0

In [41]:
int(torch.argmax(result.logits))+1

1

In [42]:
#tokens = tokenizer.encode('This is amazing, I loved it. Great', return_tensors = 'pt')

In [43]:
#tokens

In [44]:
#tokens[0]

In [45]:
#result = model(tokens)

In [46]:
#result

In [47]:
#int(torch.argmax(result.logits))+1

# 4. Collect Reviews

In [48]:
r = requests.get('https://www.yelp.com/biz/mejico-sydney-2')
soup = BeautifulSoup(r.text, 'html.parser')
regex = re.compile('.*comment.*')
results = soup.find_all('p', {'class':regex})
reviews = [result.text for result in results]

In [49]:
r.text

'<!DOCTYPE html><html lang="en-US" prefix="og: http://ogp.me/ns#" style="margin: 0;padding: 0; border: 0; font-size: 100%; font: inherit; vertical-align: baseline;"><head><script>document.documentElement.className=document.documentElement.className.replace(/\x08no-js\x08/,"js");</script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><meta http-equiv="Content-Language" content="en-US" /><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><link rel="mask-icon" sizes="any" href="https://s3-media0.fl.yelpcdn.com/assets/srv0/yelp_large_assets/b2bb2fb0ec9c/assets/img/logos/yelp_burst.svg" content="#FF1A1A"><link rel="shortcut icon" href="https://s3-media0.fl.yelpcdn.com/assets/srv0/yelp_large_assets/b05852393ae5/assets/img/logos/favicon.ico"><script> window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;window.ygaPageStartTime=new Date().getTime();</script><script async src="https://www.google-analytics.com/ana

In [50]:
soup

<!DOCTYPE html>
<html lang="en-US" prefix="og: http://ogp.me/ns#" style="margin: 0;padding: 0; border: 0; font-size: 100%; font: inherit; vertical-align: baseline;"><head><script>document.documentElement.className=document.documentElement.className.replace(/no-js/,"js");</script><meta content="text/html; charset=utf-8" http-equiv="Content-Type"/><meta content="en-US" http-equiv="Content-Language"/><meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport"/><link content="#FF1A1A" href="https://s3-media0.fl.yelpcdn.com/assets/srv0/yelp_large_assets/b2bb2fb0ec9c/assets/img/logos/yelp_burst.svg" rel="mask-icon" sizes="any"/><link href="https://s3-media0.fl.yelpcdn.com/assets/srv0/yelp_large_assets/b05852393ae5/assets/img/logos/favicon.ico" rel="shortcut icon"/><script> window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;window.ygaPageStartTime=new Date().getTime();</script><script async="" src="https://www.google-analytics.com/analy

In [51]:
results

[<p class="comment__09f24__gu0rG css-qgunke"><span class="raw__09f24__T4Ezm" lang="en">The food is fresh and tasty.  The scallop ceviche started the lunch. The scallops were tender with a great acidity and use of mango and peppers. The steak was tender and I got the hint of tequila in the sauce. I enjoyed a watermelon salad that complimented the the steak. The portions are good, but a stretch if you are sharing. My only down point is the service. They really only showed up to present my next plate and never checked to see if I wanted another drink (which I did).<br/><br/>Enjoyed the food.</span></p>,
 <p class="comment__09f24__gu0rG css-qgunke"><span class="raw__09f24__T4Ezm" lang="en">Don't come here expecting legit Mexican food but a modern twist on some staples. Loud party area, fun drinks and friendly staff make this a hip meeting area for large groups. Drinks were better than the food. <br/><br/>They stuff the families toward the back but lack any amenities (no changing table) exc

In [52]:
results[0]

<p class="comment__09f24__gu0rG css-qgunke"><span class="raw__09f24__T4Ezm" lang="en">The food is fresh and tasty.  The scallop ceviche started the lunch. The scallops were tender with a great acidity and use of mango and peppers. The steak was tender and I got the hint of tequila in the sauce. I enjoyed a watermelon salad that complimented the the steak. The portions are good, but a stretch if you are sharing. My only down point is the service. They really only showed up to present my next plate and never checked to see if I wanted another drink (which I did).<br/><br/>Enjoyed the food.</span></p>

In [53]:
reviews

['The food is fresh and tasty. \xa0The scallop ceviche started the lunch. The scallops were tender with a great acidity and use of mango and peppers. The steak was tender and I got the hint of tequila in the sauce. I enjoyed a watermelon salad that complimented the the steak. The portions are good, but a stretch if you are sharing. My only down point is the service. They really only showed up to present my next plate and never checked to see if I wanted another drink (which I did).Enjoyed the food.',
 "Don't come here expecting legit Mexican food but a modern twist on some staples. Loud party area, fun drinks and friendly staff make this a hip meeting area for large groups. Drinks were better than the food. They stuff the families toward the back but lack any amenities (no changing table) except a high chair. Service started off friendly but it took a while to get someone to take our order and then they forgot our dish which came out cold when we asked for it. Then we had to flag someo

# 5. Load Reviews into DataFrame and Score

In [54]:
import numpy as np
import pandas as pd

In [55]:
df = pd.DataFrame(np.array(reviews), columns = ['review'])

In [56]:
df.head()

review
0  The food is fresh and tasty.  The scallop cevi...
1  Don't come here expecting legit Mexican food b...
2  Out of all the restaurants that I tried in Syd...
3  We came here on a Thursday night @ 5pm and by ...
4  I was pleasantly surprised at what a great job...

In [57]:
df.tail()

review
5  Really nice (upmarket) Mexican restaurant. Goo...
6  Have been here twice and have absolutely loved...
7  Ordered feed me for $59 along with that.. Food...
8  The best tasting cauliflower taco, mushroom ce...
9  If you're looking for a quiet little romantic ...

In [58]:
df.iloc[0]

review    The food is fresh and tasty.  The scallop cevi...
Name: 0, dtype: object

In [59]:
df['review'].iloc[0]

'The food is fresh and tasty. \xa0The scallop ceviche started the lunch. The scallops were tender with a great acidity and use of mango and peppers. The steak was tender and I got the hint of tequila in the sauce. I enjoyed a watermelon salad that complimented the the steak. The portions are good, but a stretch if you are sharing. My only down point is the service. They really only showed up to present my next plate and never checked to see if I wanted another drink (which I did).Enjoyed the food.'

In [60]:
df['review'].iloc[1]

"Don't come here expecting legit Mexican food but a modern twist on some staples. Loud party area, fun drinks and friendly staff make this a hip meeting area for large groups. Drinks were better than the food. They stuff the families toward the back but lack any amenities (no changing table) except a high chair. Service started off friendly but it took a while to get someone to take our order and then they forgot our dish which came out cold when we asked for it. Then we had to flag someone down to pay the bill. The watermelon salad was tasty but not complex, tossed with a few cucumbers and pistachios. The corn lollipops with spicy mayo sauce were probably the best dish. The beef empanadas were cold and average though the salsa was an interesting pickled onion. Definitely skip the octopus dish- it was dry, over cooked and lacked flavor though the presentation looked promising. It came with squares of polenta and dallops of potato mash with a dramatic squid ink streak across the dish bu

In [61]:
def sentiment_score(review):
    tokens = tokenizer.encode(review, return_tensors = 'pt')
    result = model(tokens)
    return int(torch.argmax(result.logits))+1

In [62]:
sentiment_score(df['review'].iloc[0])

4

In [63]:
sentiment_score(df['review'].iloc[1])

3

In [64]:
sentiment_score(df['review'].iloc[6])

5

In [65]:
df['sentiment'] = df['review'].apply(lambda x : sentiment_score(x[:512]))

In [66]:
df

review  sentiment
0  The food is fresh and tasty.  The scallop cevi...          4
1  Don't come here expecting legit Mexican food b...          3
2  Out of all the restaurants that I tried in Syd...          5
3  We came here on a Thursday night @ 5pm and by ...          4
4  I was pleasantly surprised at what a great job...          5
5  Really nice (upmarket) Mexican restaurant. Goo...          4
6  Have been here twice and have absolutely loved...          5
7  Ordered feed me for $59 along with that.. Food...          2
8  The best tasting cauliflower taco, mushroom ce...          5
9  If you're looking for a quiet little romantic ...          2